/* Vector table declaration for Energy Micro (SiLabs) EFM32GG Giant Gecko microcontrollers. */
/* NMI_Handler 2 */
/* HardFault_Handler 3 */
/* MemManage_Handler 4 */
/* BusFault_Handler 5 */
/* UsageFault_Handler 6 */
/* Reserved 7 */
/* Reserved 8 */
/* Reserved 9 */
/* Reserved 10 */
/* SVC_Handler 11 */
/* DebugMon_Handler 12 */
/* Reserved 13 */
/* PendSV_Handler 14 */
/* SysTick_Handler 15 */
BSPACM_INC_EXPAND_IRQ_REFERENCE(DMA)           /* 16 : DMA Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(GPIO_EVEN)     /* 17 : GPIO_EVEN Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER0)        /* 18 : TIMER0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART0_RX)     /* 19 : USART0_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART0_TX)     /* 20 : USART0_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(ACMP0)         /* 21 : ACMP0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(ADC0)          /* 22 : ADC0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(DAC0)          /* 23 : DAC0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(I2C0)          /* 24 : I2C0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(GPIO_ODD)      /* 25 : GPIO_ODD Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER1)        /* 26 : TIMER1 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART1_RX)     /* 27 : USART1_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART1_TX)     /* 28 : USART1_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LESENSE)       /* 29 : LESENSE Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LEUART0)       /* 30 : LEUART0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LETIMER0)      /* 31 : LETIMER0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(PCNT0)         /* 32 : PCNT0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(RTC)           /* 33 : RTC Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(CMU)           /* 34 : CMU Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(VCMP)          /* 35 : VCMP Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LCD)           /* 36 : LCD Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(MSC)           /* 37 : MSC Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(AES)           /* 38 : AES Interrupt */

/*
 * Local Variables:
 * mode:c
 * End:
 */
