#!/bin/sh
# reindent - wrapper to invoke style with BSPACM formatting standards
#
# Written in 2014 by Peter A. Bigot <http://www.pabigot.com>
#
# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to
# the public domain worldwide. This software is distributed without
# any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication
# along with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#

# http://sourceforge.net/projects/astyle/
astyle \
  --options=none \
  --style=1tbs \
  --convert-tabs \
  --indent=spaces=2 \
  --indent-switches \
  --max-instatement-indent=60 \
  --pad-header \
  -r \
      '*.c' \
      '*.h' \
      '*.inc'
