# http://www.ti.com/product/tm4c1294ncpdt
DEVICE=tm4c1294ncpdt

# TivaWare wants to know which silicon revision it's targeting
# so it adjusts for errata and changes to the ROM.
TIVAWARE_TARGET ?= TM4C129_RA0

include $(BSPACM_ROOT)/device/tm4c/tm4c129/Makefile.line

# Local Variables:
# mode:makefile
# End:
