/* Vector table declaration for Energy Micro (SiLabs) EFM32GG Giant Gecko microcontrollers. */
/* NMI_Handler 2 */
/* HardFault_Handler 3 */
/* MemManage_Handler 4 */
/* BusFault_Handler 5 */
/* UsageFault_Handler 6 */
/* Reserved 7 */
/* Reserved 8 */
/* Reserved 9 */
/* Reserved 10 */
/* SVC_Handler 11 */
/* DebugMon_Handler 12 */
/* Reserved 13 */
/* PendSV_Handler 14 */
/* SysTick_Handler 15 */
BSPACM_INC_EXPAND_IRQ_REFERENCE(DMA)           /* 16 : DMA Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(GPIO_EVEN)     /* 17 : GPIO_EVEN Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER0)        /* 18 : TIMER0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART0_RX)     /* 19 : USART0_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART0_TX)     /* 20 : USART0_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USB)           /* 21 : USB Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(ACMP0)         /* 22 : ACMP0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(ADC0)          /* 23 : ADC0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(DAC0)          /* 24 : DAC0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(I2C0)          /* 25 : I2C0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(I2C1)          /* 26 : I2C1 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(GPIO_ODD)      /* 27 : GPIO_ODD Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER1)        /* 28 : TIMER1 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER2)        /* 29 : TIMER2 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(TIMER3)        /* 30 : TIMER3 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART1_RX)     /* 31 : USART1_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART1_TX)     /* 32 : USART1_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LESENSE)       /* 33 : LESENSE Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART2_RX)     /* 34 : USART2_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(USART2_TX)     /* 35 : USART2_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(UART0_RX)      /* 36 : UART0_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(UART0_TX)      /* 37 : UART0_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(UART1_RX)      /* 38 : UART1_RX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(UART1_TX)      /* 39 : UART1_TX Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LEUART0)       /* 40 : LEUART0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LEUART1)       /* 41 : LEUART1 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LETIMER0)      /* 42 : LETIMER0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(PCNT0)         /* 43 : PCNT0 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(PCNT1)         /* 44 : PCNT1 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(PCNT2)         /* 45 : PCNT2 Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(RTC)           /* 46 : RTC Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(BURTC)         /* 47 : BURTC Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(CMU)           /* 48 : CMU Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(VCMP)          /* 49 : VCMP Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(LCD)           /* 50 : LCD Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(MSC)           /* 51 : MSC Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(AES)           /* 52 : AES Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(EBI)           /* 53 : EBI Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(EMU)           /* 54 : EMU Interrupt */
BSPACM_INC_EXPAND_IRQ_REFERENCE(FPUEH)         /* 55 : FPUEH Interrupt */

/*
 * Local Variables:
 * mode:c
 * End:
 */
