# http://www.silabs.com/products/mcu/lowpower/pages/efm32tg-stk3300.aspx

# This is an STK-style board, as opposed to a DK-style board.  This
# affects which kit BSP file needs to be used.
BOARD_STYLE=stk

include $(BSPACM_ROOT)/device/efm32/efm32tg/efm32tg840f32/Makefile.device

# Local Variables:
# mode:makefile
# End:
