/* BSPACM - UART0 configuration include file for nRF51822-Beacon (PCA20006)
 *
 * Written in 2014 by Peter A. Bigot <http://pabigot.github.io/bspacm/>
 *
 * To the extent possible under law, the author(s) have dedicated all
 * copyright and related and neighboring rights to this software to
 * the public domain worldwide. This software is distributed without
 * any warranty.
 *
 * You should have received a copy of the CC0 Public Domain Dedication
 * along with this software. If not, see
 * <http://creativecommons.org/publicdomain/zero/1.0/>.
 */

/* UART0 pin assignments for PCA20006 "nRF51822-Beacon" */

#define NRF51_UART0_RXD_PIN 24
#define NRF51_UART0_TXD_PIN 9
#define NRF51_UART0_RTS_PIN 11
#define NRF51_UART0_CTS_PIN 21

/*
 * Local Variables:
 * mode:c
 * End:
 */
